import { Component, OnInit } from '@angular/core';

/**
 *
 *
 * @export
 * @class HomePageComponent
 * @implements {OnInit}
 */
@Component({
  selector: 'app-home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.css']
})

export class HomePageComponent implements OnInit {
/**
 * constructor
 */
  constructor() { }
  
/**
 * Autogenerated placeholder function for OnInit
 */
  ngOnInit() {
  }



}
