import { Component, OnInit } from '@angular/core';
/**
 *
 *
 * @export
 * @class LandingComponent
 * @implements {OnInit}
 */
@Component({
  selector: 'app-landing',
  templateUrl: './landing.component.html',
  styleUrls: ['./landing.component.css']
})

export class LandingComponent implements OnInit {
/**
 * constructor
 */
  constructor() { }

  /**
   * Autogenerated placeholder function for OnInit
   */
  ngOnInit() {
  }

}
